name: Deploy .NET API to Azure

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET 10
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'
          
      - name: Restore Dependencies
      run: dotnet restore ./Auth/Auth.csproj

      - name: Install EF Core CLI
        run: dotnet tool install --global dotnet-ef

      - name: Generate SQL Script
        run: dotnet ef migrations script --idempotent --output ./migrate.sql --project ./Auth/Auth.csproj

      - name: Update Azure Database
        uses: azure/sql-action@v2.2
        with:
          connection-string: ${{ secrets.PRACTICE_DEPLOY_AZURE_CONNECTION_STRING }}
          path: './migrate.sql'

      - name: Build and Publish
        run: dotnet publish ./Auth/Auth.csproj -c Release -o release_folder

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'first-deploy-test'
          publish-profile: ${{ secrets.PRACTICE_DEPLOY_AZURE_PROFILE }}
          package: release_folder